services:
  user-app:
    container_name: user-app
    build:
      context: .
      dockerfile: Dockerfile
    # expose:
    #   - 8080
    ports:
     - "8080:8080"
    networks:
      - my-network
networks:
  my-network:
    external: true
