services:
  user-service:
    container_name: user-service-1
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
#    ports:
#      - "8080:8080"
    networks:
      - my-network
networks:
  my-network:
    external: true
